FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base

WORKDIR /app

EXPOSE 5119

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src
COPY ["RatePlate.csproj", "./"]
RUN dotnet restore "./RatePlate.csproj"


COPY . .
WORKDIR "/src/."
RUN dotnet build "RatePlate.csproj" -c Release -o /app/build
RUN dotnet publish "RatePlate.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "RatePlate.dll"]